config/routes.rb
Amdb::Application.routes.draw do
  resources :ratings

  resources :actors

  resources :characters

  root :to => 'Movies#index'
  
  resources :movies

  resources :directors

end

app/models/character.rb
class Character < ActiveRecord::Base
  attr_accessible :movie_id, :name, :actor_id
  
  belongs_to :movie
  belongs_to :actor
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  # GET /characters
  # GET /characters.json
  def index
    @characters = Character.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @characters }
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
    @character = Character.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, notice: 'Character was successfully created.' }
        format.json { render json: @character, status: :created, location: @character }
      else
        format.html { render action: "new" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])

    respond_to do |format|
      if @character.update_attributes(params[:character])
        format.html { redirect_to @character, notice: 'Character was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @character.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
  <% if @character.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

      <ul>
      <% @character.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :movie_id %><br />
    <%= f.collection_select :movie_id, Movie.all, :id, :title %>
  </div>
  <div class="field">
    <%= f.label :actor_id %><br />
    <%= f.collection_select :actor_id, Actor.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', characters_path %>

app/views/characters/index.html.erb
<h1>Listing characters</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Movie</th>
    <th>Actor</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td>
    <% if character.movie.present? %>
      <%= character.movie.title %>
    <% else %>
      No movie assigned.
    <% end %>
    </td>
    <td>
    <% if character.actor.present? %>
      <%= character.actor.name %>
    <% else %>
      No actor assigned.
    <% end %>
    </td>
    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Character', new_character_path %>

app/views/characters/new.html.erb
<h1>New character</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<p>
  <b>Movie:</b>
  <% if @character.movie.present? %>
    <%= @character.movie.title %>
  <% end %>
</p>

<p>
  <b>Actor:</b>
  <% if @character.actor.present? %>
    <%= @character.actor.name %>
  <% end %>
</p>



<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>